[package]
name = "someapp"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rand = "0.8"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[profile.release]
codegen-units = 1
lto = true
strip = true
opt-level = "z"
